default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: person_os_development

test:
  <<: *default
  database: person_os_test

production:
  primary: &primary_production
    <<: *default
    database: person_os_production
    username: person_os
    password: <%= ENV["PERSON_OS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: person_os_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: person_os_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: person_os_production_cable
    migrations_paths: db/cable_migrate
